### ISSUE TITLE
(node:60498) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `msg` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by ly525** [ymm-tech/gods-pen-cli#3]
使用`gods-pen-create demo` 创建项目失败，如下

```bash
node:60498) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `msg` of 'undefined' or 'null'.
    at Object.dirCheck (/Users/lambert/.nvm/versions/node/v12.13.0/lib/node_modules/gods-pen-cli/lib/util.js:141:31)
    at projectDirCheck (/Users/lambert/.nvm/versions/node/v12.13.0/lib/node_modules/gods-pen-cli/lib/maliang-create.js:32:27)
    at /Users/lambert/.nvm/versions/node/v12.13.0/lib/node_modules/gods-pen-cli/lib/maliang-create.js:104:11
    at new Promise (<anonymous>)
    at start (/Users/lambert/.nvm/versions/node/v12.13.0/lib/node_modules/gods-pen-cli/lib/maliang-create.js:103:22)
    at Object.<anonymous> (/Users/lambert/.nvm/versions/node/v12.13.0/lib/node_modules/gods-pen-cli/bin/maliang-create:3:36)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
(node:60498) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:60498) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

怀疑原因：https://github.com/ymm-tech/gods-pen-cli/blob/66ed43d666/lib/maliang-create.js#L32 这里没有传值导致的

https://github.com/ymm-tech/gods-pen-cli/blob/66ed43d6669ba9e11b76dcf36edb547923921517/lib/util.js#L141-L145，没有设置默认值

**Comment by mingyuanwei** [comment]
谢谢指正，着急修bug，没有注意到你已经提了pr，见谅

**Comment by mingyuanwei** [comment]
已发布 1.0.6 npm，请升级最新版本
